# Generated by Django 3.0 on 2019-12-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTempModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Ярлык')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('date_with', models.CharField(max_length=64, verbose_name='Назначена с')),
                ('date_out', models.CharField(max_length=64, verbose_name='до')),
                ('type_chaim', models.CharField(max_length=64, verbose_name='Тип')),
                ('category', models.CharField(max_length=64, verbose_name='Категория')),
                ('priority', models.CharField(max_length=64, verbose_name='Приоритет')),
                ('organization', models.CharField(max_length=64, verbose_name='Организация')),
                ('master', models.CharField(max_length=64, verbose_name='Мастер')),
                ('assignee', models.CharField(max_length=64, verbose_name='Исполнитель')),
                ('info', models.CharField(max_length=64, verbose_name='Доп. информация')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('fio', models.CharField(max_length=64, verbose_name='ФИО')),
                ('email', models.CharField(max_length=64, verbose_name='Почта')),
                ('personal_bill', models.CharField(max_length=64, verbose_name='Личный счет')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('district', models.CharField(max_length=64, verbose_name='Район')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('home_number', models.CharField(max_length=64, verbose_name='Номер дома')),
                ('room_number', models.CharField(max_length=64, verbose_name='Номер квартиры')),
                ('intercom', models.CharField(max_length=64, verbose_name='Домофон')),
                ('floor', models.CharField(max_length=64, verbose_name='Этаж')),
                ('other_info', models.CharField(max_length=64, verbose_name='Доп. информация')),
            ],
        ),
    ]
